job:on-schedule:
  only:
    - schedules
    - web
  image: $CI_REGISTRY_IMAGE
  before_script:
    - ls -lisa
    - ./.gitlab/before_script.sh
  script:
    - ./.gitlab/script.sh

build_docker:
  only:
    - web
  tags:
    - docker-image-build
  script: "echo 'Building docker image..." # unused but this line is required by GitLab CI
  variables:
    TO: $CI_REGISTRY_IMAGE # $CI_REGISTRY_IMAGE is the registry space for this particular repository
    # TO can be omitted and the imaged will be push to $CI_REGISTRY_IMAGE:latest
